<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Ox9qjo\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Ox9qjo/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1Ox9qjo.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1Ox9qjo\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container1Ox9qjo\srcDevDebugProjectContainer(array(
    'container.build_hash' => '1Ox9qjo',
    'container.build_id' => '33328b47',
    'container.build_time' => 1615316382,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1Ox9qjo');
